sonar.projectKey=tugas-project-digital-skola-devops
sonar.organization=izmilia-prastika
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/coverage/**,**/loadtest/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=https://sonarcloud.io
